### ISSUE TITLE
Doubt regarding CoverVideo and Video Addition flow

### ISSUE THREAD

**Issue by ritvij14** [AmitDigga/fabric-video-editor#12]
Hello!

I am using this project as a reference for another project, where we are using Fabric. I have 2 doubts related to this:

- In the video addition flow, user first uploads and then presses the + button to add the video to the canvas. Is there a way to skip this step? So the user just needs to upload and the video is added to the canvas as well?
- For the above I tried adding from a Video Element instance made from the video File (not part of the dom). Adding it to the canvas did not work. Also, tried using `fromURL` function of `fabric.Image` but when using it like `fabric.CoverVideo.fromURL` the browser gives an error saying `fabric.CoverVideo.fromURL is not a function`. What's the right approach? Some way to add the video directly or some way to add the fromURL function to CoverVideo class as well?

**Comment by AmitDigga** [comment]
Hi @ritvij14
I am little busy in other projects.

### First part 
This problem might be solved by overriding this method
https://github.com/AmitDigga/fabric-video-editor/blob/06285e1f5c53656d514fbf4e7f72dac24020ef14/src/store/Store.ts#L91-L93

You need to call this `addVideo()` inside `addVideoResource`. Be sure to wrap `addVideo()` with  `setTimeout`, as video might not be available till next react render
https://github.com/AmitDigga/fabric-video-editor/blob/06285e1f5c53656d514fbf4e7f72dac24020ef14/src/store/Store.ts#L407

### Second Part  
I cannot provide a solution for this as I have dig deep.
