### ISSUE TITLE
Media is not clickable on Canvas when code is copied to my repo

### ISSUE THREAD

**Issue by teghmehta** [AmitDigga/fabric-video-editor#20]
Hi, I cloned your repo, copied over it all to my repo to integrate in my project. However I can't click on any images, videos, etc that I add to the canvas. When I log     canvas.on("mouse:down", function (e) {
in the editor file, e.target is always null in my repo, however in the clone it works fine. I know this isn't your issue but help would be nice, thank you!

**Comment by AmitDigga** [comment]
Hi @teghmehta 
Were you able to fix the issue?

I will close this issue as this is not a problem in this repo. Please create a new discussion thread @ https://github.com/AmitDigga/fabric-video-editor/discussions
