### ISSUE TITLE
Video in mp4 format 

### ISSUE THREAD

**Issue by tahsinchouhan** [AmitDigga/fabric-video-editor#5]
How can we export the video to mp4 format.
I have tried some methods to do so but the problem is either the mp4 exported video is not working in quick time player in mac or chrome does not support the mp4 encoding format

**Comment by AmitDigga** [comment]
This might help [stackoverflow post](https://stackoverflow.com/questions/62863547/save-canvas-data-as-mp4-javascript)

Which is suggesting to use [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm/). Not sure if it is a client side or server side library.

**Comment by AmitDigga** [comment]
@tahsinchouhan, now we are supporting mp4 downloads. We convert the webm video to mp4 with ffmpeg.wasm
Please check if that is resolved or not.
Thank You
